/*
COPYRIGHT BENJAMIN ISHERWOOD 26/03/2014
THIS SOFTWARE IS INTENDED FOR OPEN SOURCE USE, REDISTRIBUTION
IS ENCOURAGE

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES 
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR 
OTHER DEALINGS IN THE SOFTWARE.
*/
#ifndef GUI_CONTAINER
#define GUI_CONTAINER

#include "COLLECTIONS.h"

class gui
{
private:
	vector<stringIndicator> textInterface;
	vector<doubleIndicator> floatInterface;
	vector<longIndicator> integerInterface;

public:

	gui(void);
	void addTextInterface(stringIndicator newInterface);
	void addFloatInterface(doubleIndicator newInterface);
	void addIntegerInterface(longIndicator newInterface);
};

#endif